name: CI

on:
  pull_request_target:
    branches: 
      - 'main'
      - '!test-base-*'
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:

    strategy:
      matrix:
        node-version: [16.x]
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8.6.11
          run_install: |
            - recursive: true
              args: [--no-frozen-lockfile, --strict-peer-dependencies]
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Build and lint
        run: |
          pnpm package
          pnpm test

  configure:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
    - name: Pull request auto merge enabler
      if: github.event_name == 'pull_request'
      uses: poad/github-pull-request-auto-merge-enable-action@v1.0.4
      with:
        pull_request_number: ${{ github.event.pull_request.number }}
        github_token: ${{ secrets.PERSONAL_TOKEN_FOR_GITHUB_ACTIONS }}
        repository: ${{ github.event.repository.name }}
        owner: ${{ github.repository_owner }}
        merge_method: SQUASH
