name: CI

on:
  pull_request:
    branches:
      - 'main'
      - '!test-base-*'
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:

    strategy:
      matrix:
        node-version: [20.x]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        id: pnpm-install
        with:
          version: latest
          run_install: |
            - recursive: true
              args: [--no-frozen-lockfile]

      - name: Build and lint
        run: |
          pnpm package
          pnpm test
