name: CI

on:
  pull_request:
    branches:
      - 'main'
      - '!test-base-*'
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:

    strategy:
      matrix:
        node-version: [22.x]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          run_install: |
            - recursive: true
              args: [--no-frozen-lockfile]

      - uses: oven-sh/setup-bun@v2

      - name: lint
        run: bun run --bun lint
      - name: build
        run: bun run --bun build
      - name: package
        run: bun run --bun package
      - name: test
        run: bun run --vitest test
