name: CI (test)

on:
  pull_request_target:
    branches: 
      - 'main'
      - '!test-base-*'
  push:
    branches:
      - main

  workflow_dispatch:

permissions: write-all

jobs:

  test:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          run_install: |
            - recursive: true
              args: [--no-frozen-lockfile]

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 16.x
          cache: 'pnpm'

      - name: Build
        run: pnpm package

      - name: Git config
        run: |
          git config --local user.email "ken-yo@mbr.nifty.com"
          git config --local user.name "Kenji Saito"

      - name: Create base branch
        run: |
          BASE_BRANCH_NAME="test-base-$(date "+%Y%m%d-%H%M%S")"
          git switch -c "${BASE_BRANCH_NAME}"
          touch test.txt
          git add test.txt
          git commit -m "Test $(date)"
          echo "BASE_BRANCH_NAME=${BASE_BRANCH_NAME}" >> $GITHUB_ENV

      - name: Push Base
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN_FOR_GITHUB_ACTIONS }}
          branch: ${{ env.BASE_BRANCH_NAME }}

      - name: Create head branch
        run: |
          BRANCH_NAME="test-$(date "+%Y%m%d-%H%M%S")"
          git switch -c "${BRANCH_NAME}"
          touch test1.txt
          git add test1.txt
          git commit -m "Test $(date)"
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV

      - name: Push Changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN_FOR_GITHUB_ACTIONS }}
          branch: ${{ env.BRANCH_NAME }}

      - name: Create pull request
        uses: ./
        id: create-pull-request
        with:
          head_branch: ${{ env.BRANCH_NAME }}
          base_branch: ${{ env.BASE_BRANCH_NAME }}
          github_token: ${{ secrets.PERSONAL_TOKEN_FOR_GITHUB_ACTIONS }}
          repository: github-pull-requester
          owner: poad

      - name: Close pull request for test
        env:
          RESULT: ${{ steps.create-pull-request.outputs.result }}
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN_FOR_GITHUB_ACTIONS }}
        run: |
          URL=$(echo ${RESULT} | jq -r .data.url)
          echo ${URL}

          REQUEST_BODY='{ "state": "closed" }'

          curl -sSL -X PATCH \
            --url ${URL} \
            --header 'content-type: application/vnd.github.sailor-v-preview+json' \
            --header "authorization: bearer ${GH_TOKEN}" \
            --data "${REQUEST_BODY}";

          git push origin :${{ env.BRANCH_NAME }}
          git push origin :${{ env.BASE_BRANCH_NAME }}
